baseurl = "https://androidjester.github.io"
languageCode = 'en-us'
title = "AndroidJester's Blog"
keywords = ["blog", "systems"]
theme = 'hugo-theme-stack'

[pagination]
pagerSize = 5
DefaultContentLanguage = "en"
hasCJKLanguage = false

[languages.en]
languageName = "English"
languagedirection = "ltr"
# title = "Example Site"
weight = 1

[permalinks]
post = "/p/:slug/"
page = "/:slug/"


[params]
mainSections = [ "post" ]
rssFullContent = true
featuredImageField = "image"

[params.footer]
since = 2023
customText = ""

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
emoji = "üç•"
subtitle = "Sharing any form of learning along the way"

[params.sidebar.avatar]
enabled = true
local = false
# src = "img/avatar.png"
src = "https://avatars.githubusercontent.com/u/46320020?v=4"

[params.article]
headingAnchor = false
math = false
readingTime = true

[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[params.widgets.homepage]]
type = "Search"

# [[params.widgets.homepage]]
# type = "About"

# [params.widgets.homepage.params]
# limit = 5

[[params.widgets.homepage]]
type = "Categories"

[params.widgets.homepage.params]
limit = 10


[[params.widgets.page]]
type = "toc"




[menu]
# [[menu.main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"
# newtab = true

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/AndroidJester"

    [menu.social.params]
    icon = "brand-github"

  [[menu.social]]
  identifier = "twitter"
  name = "Twitter"
  url = "https://twitter.com/android_jester"

    [menu.social.params]
    icon = "brand-twitter"
  #
  # [[menu.social]]
  # identifier = "linkedin"
  # name = "Linkedin"
  # url = "https://www.linkedin.com/in/android-jester/"
  #
  #   [menu.social.params]
  #   icon = "linkedin"
  #
  # [[menu.social]]
  # identifier = "stackoverflow"
  # name = "StackOverflow"
  # url = "https://stackoverflow.com/users/15727466/kwadwo-adjei-duah"
  #
  #   [menu.social.params]
  #   icon = "stackoverflow"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4






